### ISSUE TITLE
Profile pictures on team pages float on top on Safari

### ISSUE THREAD

**Issue by Harames** [darkstars31/csc-stat-viewer#34]
On Safari 17.2.1 on MacOS 14.2.1, the profile pictures don't stay where they are supposed to when you scroll. The pictures float down the page and cover the content. See attached picture for example.

<img width="1258" alt="image" src="https://github.com/darkstars31/csc-stat-viewer/assets/7890961/607a8975-fdb3-486b-ae2c-bd7fb27501b2">

If you hover over an individual's box, the picture snaps into the right place. 

<img width="1258" alt="image" src="https://github.com/darkstars31/csc-stat-viewer/assets/7890961/04a38ee3-2559-423b-92f3-05caaaa3db56">

**Comment by darkstars31** [comment]
Thanks for submitting this issue. I'm currently unable to address this issue due to a personal life issue that requires a large amount of my time. I'll try to get to this when I have some time, but I currently don't have a time line.

**Comment by darkstars31** [comment]
lul actually nvm, I had a `fixed` element inside of a `relative` div which apparently works for Firefox and Chrome but not Safari. The correct classname I should have used is `absolute` which resolves this issue.

Again thanks for reporting this issue and finding bugs!
