### ISSUE TITLE
Standing Stat Headers are wrong

### ISSUE THREAD

**Issue by saschakovac** [darkstars31/csc-stat-viewer#40]
![image](https://github.com/darkstars31/csc-stat-viewer/assets/143137505/43998d55-4408-4236-b952-a037746477da)

In the above image you can see the headers are all fine until the Strength of Schedule.

The first % is CT win %, next is T win %, next is Pistol win %, and the final column is SoS. The headers are just missing so probably just add the header tags back in

**Comment by darkstars31** [comment]
I was trying to fix the issue with mobile not collapsing some columns but it looks like I made it worse. I've restored the column headers for now.
