### ISSUE TITLE
Weapons leaderboard missing some query results last few days

### ISSUE THREAD

**Issue by djlarsu** [darkstars31/csc-stat-viewer#42]
I think the weapon leader board broke a few days ago, and is no longer showing zeuses and knives for me.
![Screenshot_20240830-080817](https://github.com/user-attachments/assets/c05aa53b-51fd-4a2f-92d6-36e88c2d6a17)

**Comment by darkstars31** [comment]
Thanks for alerting me to this issue. I made an "optimization" in my demo aggregation code to remove matches with existing matchids from being processed during my new match analysis/creation. Unfortunately I never separated out the portion that compiles all of the weapon leaderboards/extended stats from this code, so it only processed the new matches coming in and did not include  all of the pre-existing matches. I will get this fixed.

**Comment by darkstars31** [comment]
I should probably write some tests to cover this code to avoid issues like this in the future

**Comment by darkstars31** [comment]
Can you confirm this is fixed and working as intended?

**Comment by djlarsu** [comment]
Lgtm

**Comment by darkstars31** [comment]
Thanks again for alerting me!
